name: 'externals'

type: 'php:7.1'
build:
    flavor: composer

runtime:
    extensions:
        # Enable the event PHP extension, which provides a faster core event loop.
        - event
        - newrelic
        -
            name: 'blackfire'
            configuration:
                server_id: '69b9589f-b986-4d85-af21-cb8cedd55389'
                server_token: 'e8de86bb7a3c8d10975ba4143c31193cee56742718dc34296d513a94f7473125'

dependencies:
    nodejs:
        gulp: "^3.9"

# The hooks that will be triggered when the package is deployed.
hooks:
    # Build hooks can modify the application files on disk but not access any services like databases.
    build: |
        set -e
        npm install
        gulp
        # Optimize composer
        composer dump-autoload --classmap-authoritative
    deploy: |
        set -e
        make cache

# The size of the persistent disk of the application (in MB).
disk: 512

# The mounts that will be performed when the package is deployed.
mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"

relationships:
    database: "database:mysql"

web:
    commands:
        start: ./console serve
    upstream:
        socket_family: tcp
        protocol: http

crons:
    # Look for new emails every 5 minutes.
    sync:
        spec: '*/5 * * * *'
        cmd: './console sync'
