#!/usr/bin/env php
<?php
declare(strict_types = 1);

use Externals\Application\Application;
use Externals\Application\Command\DbCommand;
use Externals\EmailSynchronizer;
use Symfony\Bridge\Monolog\Handler\ConsoleHandler;
use Symfony\Component\Console\Output\ConsoleOutput;

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/.puli/GeneratedPuliFactory.php';

$application = new Application;
$cli = $application->cli();

$cli->command('db [--force]', [DbCommand::class, 'setup']);
$cli->command('db-purge [--force]', [DbCommand::class, 'purge']);
$cli->command('db-truncate [--force]', [DbCommand::class, 'truncate']);

$cli->command('sync [max]', function (int $max = null, EmailSynchronizer $synchronizer) {
    $synchronizer->synchronize($max);
});

$output = new ConsoleOutput();
$application->getContainer()->get(ConsoleHandler::class)->setOutput($output);
$cli->run(null, $output);
