service: externals
bref:
    team: bref

provider:
    name: aws
    region: eu-west-1
    stage: prod
    timeout: 10
    environment:
        APP_ENV: production
        APP_DEBUG: 'false'
        APP_KEY: ${ssm:/externals/app_key}
        APP_VERSION: ${env:GITHUB_RUN_ID}
        APP_URL: 'https://externals.io'
        LOG_CHANNEL: stderr
        DB_CONNECTION: mysql
        DB_DATABASE: 'externals-prod'
        DB_HOST: ${ssm:/externals/db/host}
        DB_PORT: 3306
        DB_USERNAME: ${ssm:/externals/db/user}
        DB_PASSWORD: ${ssm:/externals/db/password}
        SESSION_DRIVER: cookie
        SESSION_ENCRYPT: 'true'
        CACHE_STORE: array
        QUEUE_CONNECTION: sync
        ALGOLIA_APP_ID: KSTITII7EC
        ALGOLIA_API_KEY: ${ssm:/externals/algolia_api_key}
        ALGOLIA_INDEX_PREFIX: ${param:algoliaIndexPrefix}
        GITHUB_CLIENT_ID: ${param:githubOAuthClientId}
        GITHUB_CLIENT_SECRET: ${ssm:/externals/github_oauth_client_secret}
        GITHUB_REDIRECT_URI: 'https://externals.io/login'
        SENTRY_LARAVEL_DSN: ${ssm:/externals/sentry_url}
        # https://bref.sh/docs/environment/performances.html#bref-for-event-driven-functions
        BREF_LOOP_MAX: '100'

params:
    prod:
        isProd: true
        algoliaIndexPrefix: v2_
        githubOAuthClientId: b75b3226c86d801a95cd
    default:
        isProd: false
        algoliaIndexPrefix: dev_
        githubOAuthClientId: 422ae3a54f6ebd43895b

package:
    patterns:
        - '!.github/**'
        - '!node_modules/**'
        - '!tests/**'
        - '!storage/logs/**'
        - '!storage/framework/cache/**'
        - '!storage/framework/sessions/**'
        - '!storage/framework/views/**'
        - '!resources/css/**'
        - '!resources/js/**'

functions:
    web:
        handler: public/index.php
        runtime: php-85-fpm
        events:
            - httpApi: '*'

    # Synchronize new emails from PHP's NNTP server every 15 minutes.
    sync:
        handler: artisan
        runtime: php-85-console
        timeout: 900
        environment:
            BREF_LOOP_MAX: '1'
        events:
            -   schedule:
                    rate: rate(15 minutes)
                    input:
                        cli: 'externals:sync'
                    enabled: ${param:isProd}

    artisan:
        handler: artisan
        runtime: php-85-console
        timeout: 900

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/laravel-bridge

constructs:
    website:
        type: server-side-website
        assets:
            '/assets/*': public/assets
            '/build/*': public/build
            '/favicon.ico': public/favicon.ico
            '/robots.txt': public/robots.txt
        domain: externals.io
        certificate: arn:aws:acm:us-east-1:416566615250:certificate/0f28e63d-d3a9-4578-9f8b-14347bfe8326
