name: build

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'
                    coverage: none

            -   uses: ramsey/composer-install@v4

            -   name: PHPUnit
                run: vendor/bin/phpunit --colors=always

            -   name: PHPStan
                run: vendor/bin/phpstan analyse --memory-limit=1G --no-progress
